Call aiXplain discover models
aixplain/aiXtend pull request #3
Opened 2022-09-02 01:06 UTC by lucas-aixplain

This PR updates the code to call models passing the url and api key, as we already have with pipelines. It is changing the folder structure by having factories, that create model or pipeline objects.

Also, this PR adds methods to call models or pipelines asynchronously.

2022-09-02 11:06 UTC, krishnadurai requested changes
I left a few comments, please address them

2022-09-02 11:06 UTC, krishnadurai commented on aixplain/modules/model.py
> +            except:
`except Exception as e:`

A plain `except` catches many other undesirable exceptions like Control + C exit as well.

2022-09-02 11:06 UTC, krishnadurai commented on aixplain/modules/model.py
> +            except:
Same as above

2022-09-02 11:06 UTC, krishnadurai commented on aixplain/modules/model.py
> +        except:
Same as above

2022-09-02 11:17 UTC, lucas-aixplain commented on README.md
> +pip install aixplain
I was unsure about this because since we're changing the folder name, I thought we also needed to change the package name.

2022-09-07 12:27 UTC, krishnadurai requested changes
As discussed several times, let us not name the module 'aixplain_sdk', that would corrupt the namespace for future packages.

2022-10-31 13:18 UTC, krishnadurai approved these changes

2022-10-31 13:18 UTC, krishnadurai commented on tests/model_test.py
> +def test_mt1():
Call all of these unit tests as functional tests. Mock the backend calls for unit tests.

2022-10-31 13:18 UTC, krishnadurai commented on tests/model_test.py
> +    data = 'https://aixplain-platform-assets.s3.amazonaws.com/samples/en/bestofyou.txt'
Can we have a direct file upload for audio and video formats?

2022-10-31 13:18 UTC, merged